'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class AppointmentToolTip

    ''' <summary>
    ''' buttonDiv control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected buttonDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    ''' <summary>
    ''' btnShowMenu control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnShowMenu As Global.DevExpress.Web.ASPxButton
End Class
